### ISSUE TITLE
Doesn't work if you click on a video on YT

### ISSUE THREAD

**Issue by ailin-nemui** [vayan/external-video#12]
if you ctrl+click/open in new tab/paste yt video url, it works, but not if you click on a "link" on yt main page. My guess is they use some ajax based background loading when you click instead of regularly navigating the link, so the extension doesn't catch it

**Comment by vayan** [comment]
Yeah it was on purpose, if you're on youtube.com I assume you want to open video in it, but I assumed wrong apparently 😄
