### ISSUE TITLE
Feature Request: Option to add your own sites

### ISSUE THREAD

**Issue by h633537** [vayan/external-video#14]
I'd like to add various sites like twitch.tv. I tried to edit the xpi myself and add twitch.tv to the list on external-video.js but I can't run it because firefox blocks all unsigned addons. An option field in the preferences to add sites would be very useful.

**Comment by vayan** [comment]
Hard to add additional websites as an option because of the manifest 🤔 Or I can ask access to all websites but I wanted to avoid that. 
Anyway I'll add support for Twitch! it's a perfect fit for this add-on

**Comment by dinotheextinct** [comment]
When I open twitch.tv with the addon enabled, it doesnt load the website, it instead tries to load a video and stops after some seconds. How can I prevent that? Only work around is to always deactivate the addon before accessing twitch.tv.
